security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~

# we use guard instead to automatically login the user after activation or password reset
#            form_login:
#                login_path: security_login
#                check_path: security_login
#                username_parameter: login[_username]
#                password_parameter: login[_password]
#                remember_me: true

            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                    - App\Security\OAuthAuthenticator
                entry_point: App\Security\LoginFormAuthenticator

            remember_me:
                secret:   '%kernel.secret%'
                remember_me_parameter: login[remember_me]
                lifetime: 604800 # 1 week in seconds
                path: /

            logout:
                path: security_logout
